# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test - ${{ matrix.config.python }} - ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}

    strategy:
      matrix:
        config:
          - os: ubuntu-latest
            python: 3.7
          - os: ubuntu-latest
            python: 3.8
          - os: ubuntu-latest
            python: 3.9

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.config.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.config.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Info
        run: |
          echo "=====  PYTHON  ====="
          python --version
      - name: Run tests
        run: tox -e py${{ matrix.config.python }}
